- name: Install Packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - btop
      - git
      - fzf
      - syncthing
      - fd-find
      - fastfetch
      - zoxide
      - bat
      - helix
      - micro
      - ranger
      - vim
      - tmux
      - rofi

